In [15]:
#8cm
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy.optimize
import scipy.stats

x_values = 0.001*np.array([ 381.452,  573.572,  766.011,  957.873, 1149.144, 1341.823,
       1724.636, 2109.346, 2493.271, 2876.56 , 3259.85 , 3644.417,
       4027.672, 4412.564, 4796.014, 5164.327, 5356.747, 5548.1  ,
       5740.109, 6123.74 , 6507.587, 6891.892, 7275.51 , 7659.531,
       8043.059, 8427.893, 8811.595, 9195.209, 9563.59 , 9755.299])
y_values = 0.001*np.array([ 1.526,  1.882,  2.238,  2.595,  2.952,  3.308,  4.022,  4.733,
        5.448,  6.161,  6.872,  7.585,  8.297,  9.009,  9.72 , 10.431,
       10.788, 11.144, 11.499, 12.21 , 12.919, 13.63 , 14.342, 15.054,
       15.764, 16.475, 17.184, 17.895, 18.606, 18.96 ])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 431.471,  814.899, 1182.928, 1374.911, 1566.115, 1758.993,
       1950.16 , 2334.843, 2718.899, 3102.436, 3486.159, 3870.395,
       4254.235, 4638.569, 5022.45 , 5405.816, 5773.113, 5964.81 ,
       6157.411, 6350.1  , 6540.949, 6733.816, 7117.078, 7500.744,
       7885.427, 8269.583, 8652.915, 9037.372, 9420.82 , 9803.889])
y_values = 0.001*np.array([ 1.118,  1.831,  2.536,  2.89 ,  3.245,  3.6  ,  3.954,  4.663,
        5.37 ,  6.078,  6.786,  7.494,  8.201,  8.912,  9.619, 10.327,
       11.034, 11.388, 11.741, 12.096, 12.448, 12.801, 13.507, 14.215,
       14.921, 15.627, 16.333, 17.041, 17.746, 18.452])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 510.462,  701.653,  894.038, 1085.645, 1277.304, 1469.31 ,
       1661.892, 2045.797, 2430.149, 2813.555, 3197.431, 3581.522,
       3965.87 , 4349.235, 4732.516, 5116.67 , 5485.331, 5676.982,
       5869.416, 6060.956, 6252.958, 6636.718, 7021.123, 7404.577,
       7788.205, 8172.352, 8556.144, 8939.953, 9323.093, 9707.721])
y_values = 0.001*np.array([ 1.365,  1.724,  2.087,  2.442,  2.799,  3.158,  3.515,  4.234,
        4.952,  5.659,  6.374,  7.09 ,  7.804,  8.516,  9.229,  9.942,
       10.654, 11.012, 11.365, 11.72 , 12.082, 12.793, 13.508, 14.218,
       14.934, 15.645, 16.355, 17.066, 17.777, 18.489])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0018592536583062784, 0.0018487210270058114, 0.0018628502403451555])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00185925 0.0008147 ] 

Covariance matrix = 
 [[ 3.91478320e-15 -1.88664352e-14]
 [-1.88664352e-14  1.24255962e-13]]
chi^2_min = 1922.6705265325295
reduced chi^2 = 68.66680451901891
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0018592536583062784 units?
best fit intercept = 0.0008147031302131664 units?
[6.25682284e-08 3.52499591e-07]
optimised parameter[0] = (0.0018592536583062784 +/- 6.256822838575609e-08) units
optimised parameter[1] = (0.0008147031302131664 +/- 3.524995911940037e-07) units
Optimised parameters =  [0.00184872 0.00034301] 

Covariance matrix = 
 [[ 4.34622739e-15 -2.16038367e-14]
 [-2.16038367e-14  1.40719743e-13]]
chi^2_min = 3259.0297221195265
reduced chi^2 = 116.39391864712594
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0018487210270058114 units?
best fit intercept = 0.00034301020082426914 units?
[6.59259235e-08 3.75126303e-07]
optimised parameter[0] = (0.0018487210270058114 +/- 6.592592354053281e-08) units
optimised parameter[1] = (0.0003430

In [16]:
#9cm
x_values = 0.001*np.array([ 525.514,  910.144, 1294.297, 1661.922, 1853.848, 2046.285,
       2238.396, 2430.085, 2814.082, 3197.325, 3581.39 , 3965.066,
       4348.92 , 4733.157, 5117.911, 5500.732, 5885.05 , 6252.986,
       6444.263, 6637.329, 6828.681, 7020.765, 7211.936, 7404.521,
       7788.832, 8172.934, 8555.984, 8940.156, 9324.077, 9707.559])
y_values = 0.001*np.array([ 1.256,  2.035,  2.814,  3.592,  3.981,  4.368,  4.757,  5.145,
        5.925,  6.703,  7.479,  8.257,  9.036,  9.812, 10.585, 11.363,
       12.142, 12.915, 13.302, 13.69 , 14.078, 14.466, 14.854, 15.242,
       16.016, 16.791, 17.564, 18.341, 19.112, 19.887])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 543.177,  927.352, 1294.9  , 1487.406, 1678.798, 1871.499,
       2062.963, 2255.157, 2638.924, 3022.86 , 3406.083, 3791.161,
       4174.299, 4558.332, 4942.259, 5325.83 , 5709.927, 6077.367,
       6270.241, 6461.969, 6654.307, 6846.392, 7229.853, 7612.821,
       7996.652, 8381.776, 8765.924, 9149.331, 9533.61 , 9917.389])
y_values = 0.001*np.array([ 1.374,  2.144,  2.916,  3.304,  3.69 ,  4.074,  4.458,  4.844,
        5.614,  6.384,  7.154,  7.924,  8.693,  9.46 , 10.23 , 10.997,
       11.767, 12.533, 12.919, 13.303, 13.684, 14.069, 14.836, 15.603,
       16.371, 17.139, 17.904, 18.674, 19.439, 20.208])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 527.173,  718.943, 1103.705, 1486.917, 1871.399, 2255.383,
       2639.043, 3022.756, 3407.097, 3775.036, 3966.031, 4158.899,
       4350.886, 4542.859, 4734.04 , 4925.996, 5310.626, 5694.537,
       6078.361, 6461.673, 6845.785, 7229.44 , 7612.814, 7997.419,
       8365.527, 8557.213, 8749.189, 8941.106, 9132.915, 9325.114])
y_values = 0.001*np.array([ 1.188,  1.584,  2.378,  3.163,  3.95 ,  4.733,  5.525,  6.303,
        7.09 ,  7.882,  8.271,  8.663,  9.059,  9.451,  9.841, 10.234,
       11.02 , 11.803, 12.586, 13.372, 14.166, 14.939, 15.719, 16.506,
       17.288, 17.681, 18.089, 18.469, 18.851, 19.249])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0020292352196211085, 0.002008058258469196, 0.0020525494071899878])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00202924 0.00020881] 

Covariance matrix = 
 [[ 4.58185374e-15 -2.32749214e-14]
 [-2.32749214e-14  1.51565377e-13]]
chi^2_min = 3932.377956688277
reduced chi^2 = 140.4420698817242
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0020292352196211085 units?
best fit intercept = 0.00020881432162120591 units?
[6.76893916e-08 3.89313982e-07]
optimised parameter[0] = (0.0020292352196211085 +/- 6.768939161897685e-08) units
optimised parameter[1] = (0.00020881432162120591 +/- 3.8931398204510406e-07) units
Optimised parameters =  [0.00200806 0.00031061] 

Covariance matrix = 
 [[ 4.27597311e-15 -2.14637554e-14]
 [-2.14637554e-14  1.41073210e-13]]
chi^2_min = 3991.1015260987933
reduced chi^2 = 142.53934021781404
P(chi^2_min, DoF) = 0.0
best fit slope = 0.002008058258469196 units?
best fit intercept = 0.0003106133489455731 units?
[6.53909253e-08 3.75597139e-07]
optimised parameter[0] = (0.002008058258469196 +/- 6.539092528264798e-08) units
optimised parameter[1] = (0.00031061

In [17]:
#10cm
x_values = 0.001*np.array([ 350.629,  543.304,  734.599,  927.291, 1118.573, 1310.741,
       1695.121, 2078.766, 2462.767, 2846.109, 3229.87 , 3613.547,
       3997.203, 4381.569, 4764.843, 5133.772, 5326.02 , 5518.116,
       5709.36 , 5901.915, 6285.874, 6669.747, 7053.775, 7437.512,
       7821.294, 8205.504, 8588.849, 8972.593, 9356.057, 9724.431])
y_values = 0.001*np.array([ 1.113,  1.534,  1.949,  2.361,  2.773,  3.184,  4.01 ,  4.832,
        5.656,  6.478,  7.302,  8.125,  8.951,  9.776, 10.603, 11.434,
       11.847, 12.261, 12.676, 13.094, 13.923, 14.747, 15.568, 16.396,
       17.227, 18.056, 18.882, 19.713, 20.545, 21.374])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  510.218,   893.218,  1277.245,  1661.568,  2030.081,  2221.643,
        2413.947,  2604.51 ,  2797.816,  3181.176,  3564.392,  3949.29 ,
        4332.568,  4716.568,  5100.456,  5484.65 ,  5869.136,  6252.192,
        6620.422,  6811.513,  7004.571,  7196.758,  7580.194,  7963.604,
        8347.727,  8731.079,  9115.672,  9499.907,  9884.089, 10267.888])
y_values = 0.001*np.array([ 1.386,  2.215,  3.047,  3.868,  4.701,  5.111,  5.517,  5.929,
        6.341,  7.164,  7.988,  8.811,  9.631, 10.453, 11.275, 12.096,
       12.916, 13.745, 14.571, 14.983, 15.398, 15.814, 16.642, 17.472,
       18.302, 19.132, 19.958, 20.789, 21.615, 22.439])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  510.643,   702.828,  1086.544,  1278.19 ,  1470.302,  1854.064,
        2238.322,  2621.536,  3005.087,  3389.521,  3773.591,  4157.205,
        4541.656,  4925.046,  5293.119,  5485.177,  5676.339,  5868.213,
        6060.637,  6252.953,  6636.537,  7020.143,  7404.394,  7788.067,
        8172.628,  8555.16 ,  8940.439,  9323.886,  9707.174, 10075.578])
y_values = 0.001*np.array([ 1.71 ,  2.135,  2.979,  3.4  ,  3.821,  4.658,  5.501,  6.343,
        7.184,  8.023,  8.863,  9.705, 10.545, 11.387, 12.226, 12.645,
       13.066, 13.487, 13.906, 14.327, 15.167, 16.007, 16.85 , 17.691,
       18.534, 19.375, 20.217, 21.058, 21.903, 22.744])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0021585140230151695, 0.002156025579785901, 0.0021966654948233993])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00215851 0.00034665] 

Covariance matrix = 
 [[ 4.09490690e-15 -1.93497673e-14]
 [-1.93497673e-14  1.24767286e-13]]
chi^2_min = 5764.697686323921
reduced chi^2 = 205.8820602258543
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0021585140230151695 units?
best fit intercept = 0.000346652985840202 units?
[6.39914596e-08 3.53224129e-07]
optimised parameter[0] = (0.0021585140230151695 +/- 6.39914595833771e-08) units
optimised parameter[1] = (0.000346652985840202 +/- 3.5322412939099584e-07) units
Optimised parameters =  [0.00215603 0.00029689] 

Covariance matrix = 
 [[ 4.04119793e-15 -2.12680295e-14]
 [-2.12680295e-14  1.45262790e-13]]
chi^2_min = 6318.048622922987
reduced chi^2 = 225.64459367582097
P(chi^2_min, DoF) = 0.0
best fit slope = 0.002156025579785901 units?
best fit intercept = 0.00029689486928647746 units?
[6.35704171e-08 3.81133560e-07]
optimised parameter[0] = (0.002156025579785901 +/- 6.357041710163953e-08) units
optimised parameter[1] = (0.0002968948692

In [19]:
#11cm
x_values = 0.001*np.array([  382.061,   765.768,  1149.726,  1533.26 ,  1901.203,  2093.336,
        2285.235,  2476.848,  2669.277,  3052.744,  3436.551,  3820.723,
        4205.047,  4588.967,  4972.875,  5356.217,  5740.018,  6123.458,
        6507.621,  6891.342,  7259.632,  7452.1  ,  7643.321,  8027.876,
        8411.979,  8795.852,  9178.881,  9563.705,  9946.821, 10331.053])
y_values = 0.001*np.array([ 0.942,  1.842,  2.744,  3.636,  4.53 ,  4.975,  5.42 ,  5.864,
        6.309,  7.201,  8.096,  8.985,  9.879, 10.771, 11.667, 12.56 ,
       13.454, 14.347, 15.242, 16.134, 17.027, 17.474, 17.921, 18.812,
       19.703, 20.595, 21.485, 22.376, 23.268, 24.156])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 399.245,  782.658, 1166.037, 1549.972, 1933.842, 2318.438,
       2702.291, 3085.868, 3470.435, 3854.109, 4238.448, 4606.387,
       4797.839, 4990.195, 5181.134, 5372.979, 5756.759, 6141.345,
       6525.858, 6909.217, 7292.831, 7677.136, 8061.149, 8444.331,
       8827.708, 9195.913, 9388.483, 9580.598, 9772.357, 9964.957])
y_values = 0.001*np.array([ 1.241,  2.13 ,  3.019,  3.906,  4.798,  5.683,  6.573,  7.462,
        8.349,  9.238, 10.126, 11.015, 11.459, 11.903, 12.348, 12.793,
       13.679, 14.566, 15.452, 16.34 , 17.227, 18.114, 18.999, 19.885,
       20.77 , 21.655, 22.098, 22.543, 22.988, 23.431])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 365.405,  749.186, 1133.096, 1518.314, 1901.882, 2285.17 ,
       2653.875, 2845.838, 3037.218, 3229.769, 3421.279, 3613.035,
       3805.635, 4189.378, 4572.369, 4956.023, 5340.183, 5725.097,
       6107.76 , 6492.893, 6876.32 , 7260.111, 7628.044, 7819.979,
       8012.121, 8203.768, 8587.045, 8971.743, 9355.813, 9740.186])
y_values = 0.001*np.array([ 1.597,  2.498,  3.399,  4.306,  5.209,  6.106,  7.01 ,  7.463,
        7.915,  8.369,  8.818,  9.274,  9.722, 10.628, 11.532, 12.432,
       13.331, 14.228, 15.123, 16.022, 16.922, 17.821, 18.721, 19.172,
       19.621, 20.072, 20.974, 21.874, 22.774, 23.675])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.002332771097450417, 0.0023199350014746446, 0.002355179810266862])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [2.33277110e-03 7.29399746e-05] 

Covariance matrix = 
 [[ 3.80804055e-15 -1.98733422e-14]
 [-1.98733422e-14  1.37048058e-13]]
chi^2_min = 4835.126231131276
reduced chi^2 = 172.68307968325985
P(chi^2_min, DoF) = 0.0
best fit slope = 0.002332771097450417 units?
best fit intercept = 7.293997457196736e-05 units?
[6.17093230e-08 3.70200024e-07]
optimised parameter[0] = (0.002332771097450417 +/- 6.170932300448248e-08) units
optimised parameter[1] = (7.293997457196736e-05 +/- 3.7020002381686004e-07) units
Optimised parameters =  [0.00231994 0.00031158] 

Covariance matrix = 
 [[ 3.99043981e-15 -2.18128779e-14]
 [-2.18128779e-14  1.52568725e-13]]
chi^2_min = 3664.4431707942667
reduced chi^2 = 130.87297038550952
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0023199350014746446 units?
best fit intercept = 0.0003115764977633894 units?
[6.31699281e-08 3.90600467e-07]
optimised parameter[0] = (0.0023199350014746446 +/- 6.316992806845636e-08) units
optimised parameter[1] = (0.0

In [21]:
#12cm
x_values = 0.001*np.array([ 365.921,  749.54 , 1133.987, 1517.685, 1901.179, 2285.315,
       2669.111, 3037.55 , 3229.25 , 3421.177, 3613.125, 3805.163,
       4188.714, 4380.485, 4764.747, 5149.115, 5531.9  , 5916.332,
       6300.094, 6683.583, 7067.962, 7451.987, 7820.173, 8012.488,
       8203.225, 8395.605, 8588.084, 8780.178, 9163.279, 9547.241])
y_values = 0.001*np.array([ 1.103,  2.067,  3.018,  3.972,  4.928,  5.877,  6.833,  7.782,
        8.258,  8.735,  9.212,  9.688, 10.638, 11.117, 12.063, 13.015,
       13.965, 14.917, 15.868, 16.821, 17.769, 18.722, 19.673, 20.146,
       20.622, 21.098, 21.573, 22.049, 23.001, 23.951])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  446.461,   829.798,  1198.746,  1389.737,  1581.731,  1774.382,
        1966.037,  2350.043,  2734.114,  3117.285,  3500.968,  3884.852,
        4268.929,  4653.123,  5036.475,  5421.472,  5789.403,  5996.766,
        6365.233,  6557.243,  6748.621,  7132.928,  7516.393,  7899.522,
        8284.217,  8668.089,  9051.903,  9436.015,  9820.353, 10203.796])
y_values = 0.001*np.array([ 1.413,  2.367,  3.308,  3.783,  4.258,  4.736,  5.209,  6.154,
        7.103,  8.043,  8.993,  9.939, 10.883, 11.833, 12.777, 13.717,
       14.667, 15.136, 16.082, 16.556, 17.026, 17.972, 18.917, 19.862,
       20.803, 21.747, 22.691, 23.637, 24.579, 25.524])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  446.68 ,   638.871,   830.082,  1214.12 ,  1597.926,  1981.6  ,
        2365.785,  2750.095,  3134.123,  3518.14 ,  3901.978,  4285.848,
        4653.212,  4861.338,  5228.898,  5421.422,  5612.863,  5996.731,
        6381.411,  6764.715,  7149.128,  7532.434,  7916.167,  8300.867,
        8684.062,  9068.005,  9451.653,  9819.895, 10011.157, 10204.038])
y_values = 0.001*np.array([ 1.677,  2.156,  2.642,  3.606,  4.569,  5.52 ,  6.482,  7.443,
        8.399,  9.357, 10.314, 11.272, 12.226, 12.705, 13.655, 14.133,
       14.61 , 15.562, 16.514, 17.458, 18.41 , 19.36 , 20.308, 21.264,
       22.217, 23.17 , 24.127, 25.082, 25.56 , 26.04 ])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0024878227762519444, 0.0024695379995484735, 0.002493931850685453])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00248782 0.00020556] 

Covariance matrix = 
 [[ 4.49541807e-15 -2.30276601e-14]
 [-2.30276601e-14  1.51291923e-13]]
chi^2_min = 4319.989043385533
reduced chi^2 = 154.28532297805472
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0024878227762519444 units?
best fit intercept = 0.00020556125210121948 units?
[6.70478789e-08 3.88962624e-07]
optimised parameter[0] = (0.0024878227762519444 +/- 6.704787890526256e-08) units
optimised parameter[1] = (0.00020556125210121948 +/- 3.889626235319278e-07) units
Optimised parameters =  [0.00246954 0.00034444] 

Covariance matrix = 
 [[ 3.91550413e-15 -2.00505941e-14]
 [-2.00505941e-14  1.36008817e-13]]
chi^2_min = 5601.0046296028595
reduced chi^2 = 200.03587962867354
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0024695379995484735 units?
best fit intercept = 0.00034443754045807853 units?
[6.25739892e-08 3.68793732e-07]
optimised parameter[0] = (0.0024695379995484735 +/- 6.257398923596815e-08) units
optimised parameter[1] = (0.00034

In [23]:
#13cm
x_values = 0.001*np.array([  511.744,   895.852,  1279.541,  1647.419,  1854.737,  2223.242,
        2415.267,  2607.021,  2990.737,  3375.142,  3758.588,  4142.879,
        4525.986,  4909.452,  5294.469,  5677.529,  6061.144,  6429.143,
        6621.563,  6813.543,  7005.556,  7196.807,  7581.127,  7772.928,
        8157.288,  8540.745,  8925.203,  9309.349,  9693.286, 10076.876])
y_values = 0.001*np.array([ 1.567,  2.582,  3.598,  4.607,  5.118,  6.123,  6.632,  7.136,
        8.146,  9.155, 10.166, 11.178, 12.186, 13.195, 14.206, 15.216,
       16.225, 17.235, 17.741, 18.247, 18.751, 19.258, 20.267, 20.771,
       21.781, 22.791, 23.802, 24.811, 25.818, 26.826])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 365.389,  749.789, 1133.758, 1517.558, 1900.783, 2268.594,
       2476.441, 2844.782, 3036.851, 3229.012, 3419.812, 3612.49 ,
       3804.264, 4188.705, 4571.805, 4956.69 , 5340.706, 5724.427,
       6108.577, 6492.51 , 6859.516, 7067.044, 7436.04 , 7627.811,
       7820.094, 8204.225, 8588.086, 8971.763, 9355.527, 9739.056])
y_values = 0.001*np.array([ 1.786,  2.737,  3.779,  4.78 ,  5.735,  6.728,  7.309,  8.275,
        8.751,  9.231,  9.709, 10.205, 10.778, 11.76 , 12.713, 13.678,
       14.786, 15.731, 16.684, 17.662, 18.749, 19.212, 20.161, 20.637,
       21.117, 22.214, 23.164, 24.116, 25.082, 26.181])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  463.934,   847.082,  1231.091,  1615.62 ,  1999.169,  2382.831,
        2766.916,  3149.986,  3534.597,  3902.289,  4095.187,  4478.491,
        4671.046,  5054.93 ,  5438.635,  5822.821,  6206.686,  6590.055,
        6973.592,  7357.765,  7741.28 ,  8125.808,  8493.291,  8685.964,
        8877.577,  9261.614,  9644.822, 10029.099, 10412.723, 10797.018])
y_values = 0.001*np.array([ 3.895,  4.899,  5.909,  6.908,  7.904,  8.902,  9.897, 10.895,
       11.892, 12.886, 13.385, 14.386, 14.883, 15.888, 16.886, 17.885,
       18.886, 19.888, 20.887, 21.892, 22.894, 23.896, 24.899, 25.403,
       25.904, 26.909, 27.913, 28.916, 29.92 , 30.923])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0026407937785646496, 0.0025985874797720978, 0.002615748548414257])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00264079 0.00023709] 

Covariance matrix = 
 [[ 4.23567103e-15 -2.23493980e-14]
 [-2.23493980e-14  1.51259293e-13]]
chi^2_min = 5983.628238012721
reduced chi^2 = 213.70100850045432
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0026407937785646496 units?
best fit intercept = 0.00023709197455530566 units?
[6.50820331e-08 3.88920677e-07]
optimised parameter[0] = (0.0026407937785646496 +/- 6.508203308855068e-08) units
optimised parameter[1] = (0.00023709197455530566 +/- 3.889206769286149e-07) units
Optimised parameters =  [0.00259859 0.00083965] 

Covariance matrix = 
 [[ 4.51796705e-15 -2.25012986e-14]
 [-2.25012986e-14  1.45398878e-13]]
chi^2_min = 42869.271085427536
reduced chi^2 = 1531.0453959081262
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0025985874797720978 units?
best fit intercept = 0.0008396524872734472 units?
[6.72158244e-08 3.81312048e-07]
optimised parameter[0] = (0.0025985874797720978 +/- 6.721582441448145e-08) units
optimised parameter[1] = (0.000839

In [25]:
#14cm
x_values = 0.001*np.array([  461.801,   846.368,  1229.727,  1613.859,  1998.333,  2381.566,
        2765.638,  3149.316,  3533.452,  3901.677,  4092.61 ,  4285.127,
        4477.222,  4668.723,  4860.556,  5052.415,  5437.514,  5821.383,
        6205.316,  6589.116,  6972.695,  7355.826,  7740.082,  8123.82 ,
        8508.091,  8876.463,  9068.293,  9452.438,  9644.362, 10028.192])

y_values = 0.001*np.array([ 2.769,  3.831,  4.897,  5.963,  7.027,  8.091,  9.154, 10.216,
       11.282, 12.338, 12.874, 13.404, 13.935, 14.465, 14.996, 15.527,
       16.589, 17.65 , 18.71 , 19.769, 20.823, 21.88 , 22.934, 23.985,
       25.041, 26.091, 26.619, 27.67 , 28.196, 29.248])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 382.935,  575.229,  766.265,  958.859, 1342.454, 1726.61 ,
       2110.586, 2493.57 , 2878.646, 3262.828, 3646.232, 4030.602,
       4414.529, 4781.965, 4973.502, 5166.303, 5357.723, 5550.18 ,
       5741.407, 5933.681, 6317.952, 6701.431, 7085.296, 7468.984,
       7852.561, 8237.26 , 8620.998, 9004.415, 9388.631, 9756.634])
y_values = 0.001*np.array([ 1.835,  2.363,  2.892,  3.426,  4.487,  5.554,  6.599,  7.673,
        8.715,  9.777, 10.839, 11.896, 12.953, 14.013, 14.542, 15.069,
       15.595, 16.124, 16.656, 17.182, 18.237, 19.305, 20.353, 21.405,
       22.465, 23.519, 24.576, 25.629, 26.684, 27.74 ])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  462.812,   846.41 ,  1230.791,  1614.565,  1998.486,  2382.087,
        2765.356,  3150.58 ,  3534.334,  3917.371,  4301.123,  4668.812,
        4860.501,  5053.518,  5437.03 ,  5628.661,  6012.285,  6397.051,
        6780.737,  7164.638,  7548.128,  7932.042,  8316.238,  8700.309,
        9083.951,  9452.17 ,  9644.333,  9835.526, 10027.741, 10220.117])
y_values = 0.001*np.array([ 2.046,  3.111,  4.18 ,  5.246,  6.311,  7.374,  8.437,  9.502,
       10.561, 11.611, 12.67 , 13.727, 14.255, 14.779, 15.837, 16.357,
       17.407, 18.491, 19.501, 20.572, 21.63 , 22.684, 23.747, 24.804,
       25.866, 26.925, 27.457, 27.987, 28.518, 29.045])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0027688490730544807, 0.0027619428290974156, 0.0027638921394509152])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00276885 0.00151113] 

Covariance matrix = 
 [[ 4.30594816e-15 -2.28419042e-14]
 [-2.28419042e-14  1.54503531e-13]]
chi^2_min = 12004.17394295813
reduced chi^2 = 428.7204979627904
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0027688490730544807 units?
best fit intercept = 0.0015111291140781202 units?
[6.56197239e-08 3.93069372e-07]
optimised parameter[0] = (0.0027688490730544807 +/- 6.561972386257455e-08) units
optimised parameter[1] = (0.0015111291140781202 +/- 3.9306937205868833e-07) units
Optimised parameters =  [0.00276194 0.00078001] 

Covariance matrix = 
 [[ 4.33350617e-15 -2.11660393e-14]
 [-2.11660393e-14  1.36714112e-13]]
chi^2_min = 6241.638692690096
reduced chi^2 = 222.91566759607485
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0027619428290974156 units?
best fit intercept = 0.000780010030689035 units?
[6.58293716e-08 3.69748715e-07]
optimised parameter[0] = (0.0027619428290974156 +/- 6.582937162034052e-08) units
optimised parameter[1] = (0.0007800100

In [27]:
#15cm
x_values = 0.001*np.array([ 541.752,  909.327, 1102.6  , 1293.773, 1486.261, 1677.506,
       1869.338, 2061.632, 2446.248, 2830.087, 3213.7  , 3596.908,
       3981.759, 4365.534, 4749.528, 5133.388, 5517.163, 5885.263,
       6077.087, 6268.565, 6460.765, 6652.811, 7036.974, 7420.611,
       7804.798, 8188.054, 8571.745, 8955.906, 9339.105, 9723.673])

y_values = 0.001*np.array([ 1.897,  3.009,  3.566,  4.12 ,  4.674,  5.232,  5.788,  6.338,
        7.451,  8.55 ,  9.653, 10.758, 11.858, 12.961, 14.07 , 15.173,
       16.287, 17.395, 17.954, 18.51 , 19.064, 19.622, 20.732, 21.846,
       22.948, 24.049, 25.144, 26.24 , 27.33 , 28.428])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 478.678,  862.417, 1246.172, 1614.255, 1806.226, 1998.484,
       2189.896, 2382.148, 2574.387, 2958.456, 3342.   , 3725.141,
       4110.06 , 4493.872, 4876.942, 5261.866, 5645.856, 6029.043,
       6397.56 , 6589.476, 6780.625, 6973.195, 7164.771, 7548.605,
       7932.667, 8317.122, 8701.072, 9084.7  , 9468.382, 9851.716])
y_values = 0.001*np.array([ 3.108,  4.225,  5.34 ,  6.453,  7.012,  7.571,  8.127,  8.687,
        9.245, 10.355, 11.457, 12.555, 13.653, 14.751, 15.85 , 16.955,
       18.05 , 19.153, 20.268, 20.822, 21.375, 21.931, 22.484, 23.591,
       24.702, 25.812, 26.925, 28.031, 29.143, 30.252])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 398.069,  782.635, 1167.093, 1550.434, 1934.673, 2302.717,
       2494.14 , 2685.688, 2878.281, 3070.674, 3453.911, 3837.225,
       4220.95 , 4605.532, 4989.776, 5373.624, 5757.803, 6141.501,
       6525.218, 6892.458, 7084.7  , 7276.96 , 7469.322, 7660.633,
       7853.009, 8236.651, 8620.949, 9005.142, 9388.382, 9772.848])
y_values = 0.001*np.array([ 1.752,  2.866,  3.987,  5.103,  6.217,  7.332,  7.891,  8.447,
        9.006,  9.561, 10.672, 11.788, 12.896, 14.011, 15.121, 16.235,
       17.35 , 18.462, 19.578, 20.691, 21.248, 21.802, 22.357, 22.913,
       23.469, 24.582, 25.698, 26.812, 27.923, 29.037])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0028896077025384963, 0.0028903661764370465, 0.002910654078950932])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00288961 0.00037287] 

Covariance matrix = 
 [[ 4.33354283e-15 -2.09688393e-14]
 [-2.09688393e-14  1.34795873e-13]]
chi^2_min = 13770.407310038267
reduced chi^2 = 491.80026107279525
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0028896077025384963 units?
best fit intercept = 0.00037287227703677525 units?
[6.58296501e-08 3.67145574e-07]
optimised parameter[0] = (0.0028896077025384963 +/- 6.582965011363991e-08) units
optimised parameter[1] = (0.00037287227703677525 +/- 3.671455741808437e-07) units
Optimised parameters =  [0.00289037 0.00177184] 

Covariance matrix = 
 [[ 4.34176216e-15 -2.17675389e-14]
 [-2.17675389e-14  1.42465463e-13]]
chi^2_min = 15503.523571438642
reduced chi^2 = 553.697270408523
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0028903661764370465 units?
best fit intercept = 0.0017718397282749892 units?
[6.58920493e-08 3.77445973e-07]
optimised parameter[0] = (0.0028903661764370465 +/- 6.589204930612476e-08) units
optimised parameter[1] = (0.0017718

In [29]:
#16cm
x_values = 0.001*np.array([ 510.788,  894.483, 1278.244, 1662.096, 2045.958, 2430.28 ,
       2814.232, 3197.641, 3582.276, 3950.022, 4142.143, 4333.594,
       4525.697, 4716.826, 4909.892, 5100.681, 5484.846, 5868.814,
       6253.106, 6637.536, 7021.437, 7405.494, 7787.892, 8173.292,
       8540.941, 8731.885, 8924.891, 9115.796, 9308.352, 9500.211])

y_values = 0.001*np.array([ 1.967,  3.136,  4.302,  5.468,  6.633,  7.794,  8.951, 10.107,
       11.26 , 12.414, 12.989, 13.565, 14.136, 14.701, 15.265, 15.835,
       16.979, 18.118, 19.264, 20.417, 21.576, 22.734, 23.887, 25.041,
       26.227, 26.809, 27.379, 27.924, 28.518, 29.108])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 366.534,  750.042, 1134.28 , 1501.735, 1694.298, 1885.431,
       2077.763, 2269.843, 2462.121, 2846.197, 3229.421, 3612.772,
       3997.726, 4381.826, 4765.056, 5148.556, 5532.774, 5916.434,
       6284.003, 6477.22 , 6668.695, 6860.49 , 7053.078, 7244.789,
       7628.921, 8012.662, 8396.477, 8780.644, 9163.417, 9547.25 ])
y_values = 0.001*np.array([ 2.171,  3.328,  4.486,  5.639,  6.217,  6.798,  7.378,  7.958,
        8.535,  9.694, 10.85 , 12.   , 13.156, 14.312, 15.464, 16.619,
       17.772, 18.92 , 20.076, 20.65 , 21.223, 21.8  , 22.373, 22.951,
       24.107, 25.252, 26.408, 27.562, 28.715, 29.868])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  479.929,   863.257,  1247.717,  1630.911,  2014.748,  2398.794,
        2781.97 ,  3166.055,  3549.92 ,  3918.898,  4110.282,  4302.042,
        4686.531,  5070.612,  5454.479,  5838.035,  6222.301,  6606.232,
        6988.993,  7373.667,  7757.306,  8141.344,  8509.706,  8701.635,
        8893.267,  9277.047,  9660.853, 10044.435, 10428.065, 10813.137])
y_values = 0.001*np.array([ 2.11 ,  3.262,  4.426,  5.585,  6.749,  7.916,  9.083, 10.252,
       11.42 , 12.583, 13.168, 13.753, 14.92 , 16.089, 17.257, 18.417,
       19.578, 20.737, 21.889, 23.034, 24.174, 25.323, 26.473, 27.047,
       27.621, 28.767, 29.915, 31.06 , 32.197, 33.338])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.0030126663626835314, 0.0030153993617919716, 0.003027938588696794])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00301267 0.0004648 ] 

Covariance matrix = 
 [[ 4.58835964e-15 -2.42952667e-14]
 [-2.42952667e-14  1.61976262e-13]]
chi^2_min = 26285.898689331494
reduced chi^2 = 938.7820960475534
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0030126663626835314 units?
best fit intercept = 0.00046479728646704895 units?
[6.77374316e-08 4.02462746e-07]
optimised parameter[0] = (0.0030126663626835314 +/- 6.773743162373408e-08) units
optimised parameter[1] = (0.00046479728646704895 +/- 4.0246274642177325e-07) units
Optimised parameters =  [0.0030154 0.0010989] 

Covariance matrix = 
 [[ 4.53306957e-15 -2.20141652e-14]
 [-2.20141652e-14  1.40241787e-13]]
chi^2_min = 7815.151814148847
reduced chi^2 = 279.11256479103025
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0030153993617919716 units?
best fit intercept = 0.0010989031658235732 units?
[6.73280742e-08 3.74488701e-07]
optimised parameter[0] = (0.0030153993617919716 +/- 6.732807417078802e-08) units
optimised parameter[1] = (0.00109890