In [3]:
#8cm
%matplotlib inline
import matplotlib.pyplot as plt
import numpy 
import numpy as np
import scipy.optimize
import scipy.stats

x_values = 0.001*np.array([  494.257,   862.438,  1054.166,  1245.938,  1437.919,  1630.243,
        2013.478,  2205.003,  2589.254,  2972.77 ,  3357.142,  3741.562,
        4125.718,  4508.881,  4893.413,  5277.422,  5661.01 ,  6028.584,
        6220.389,  6412.841,  6796.917,  7180.224,  7564.549,  7947.587,
        8332.043,  8716.065,  9100.301,  9483.521,  9867.489, 10250.642])
y_values = 0.001*np.array([ 6.497, 10.011, 11.768, 13.522, 15.285, 17.039, 20.545, 22.301,
       25.809, 29.29 , 32.759, 36.225, 39.684, 43.142, 46.593, 50.048,
       53.492, 56.938, 58.659, 60.375, 63.809, 67.239, 70.672, 74.095,
       77.519, 80.936, 84.354, 87.767, 91.183, 94.594])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  493.464,   877.619,  1261.194,  1645.766,  2028.744,  2413.518,
        2781.061,  2972.283,  3164.836,  3356.023,  3548.708,  3740.501,
        4124.033,  4508.263,  4892.644,  5276.054,  5660.524,  6043.841,
        6428.305,  6811.403,  7196.051,  7563.969,  7770.629,  8140.003,
        8331.989,  8715.864,  9099.791,  9482.92 ,  9867.379, 10250.694])
y_values = 0.001*np.array([ 7.106, 10.622, 14.146, 17.655, 21.162, 24.656, 28.158, 29.901,
       31.646, 33.398, 35.148, 36.891, 40.375, 43.864, 47.348, 50.829,
       54.301, 57.778, 61.261, 64.743, 68.221, 71.702, 73.438, 76.917,
       78.657, 82.134, 85.606, 89.072, 92.531, 95.983])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 510.344,  893.854, 1277.733, 1662.191, 2046.089, 2413.998,
       2604.858, 2797.187, 2989.421, 3181.12 , 3564.728, 3949.248,
       4332.108, 4717.394, 5100.705, 5485.013, 5869.068, 6253.   ,
       6636.94 , 7004.62 , 7195.929, 7388.712, 7579.825, 7772.471,
       7963.267, 8348.567, 8732.533, 9116.423, 9499.968, 9884.301])
y_values = 0.001*np.array([ 6.085,  9.592, 13.092, 16.583, 20.089, 23.599, 25.353, 27.109,
       28.869, 30.627, 34.143, 37.65 , 41.161, 44.663, 48.163, 51.67 ,
       55.157, 58.653, 62.144, 65.624, 67.366, 69.098, 70.832, 72.563,
       74.295, 77.756, 81.215, 84.677, 88.134, 91.592])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.009020360901629602, 0.009106671691422001, 0.009134026509274827])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00902036 0.00237699] 

Covariance matrix = 
 [[ 3.78296872e-15 -1.91634818e-14]
 [-1.91634818e-14  1.30410277e-13]]
chi^2_min = 485863.8856213325
reduced chi^2 = 17352.281629333305
P(chi^2_min, DoF) = 0.0
best fit slope = 0.009020360901629602 units?
best fit intercept = 0.00237699412123363 units?
[6.15058430e-08 3.61123631e-07]
optimised parameter[0] = (0.009020360901629602 +/- 6.150584298939451e-08) units
optimised parameter[1] = (0.00237699412123363 +/- 3.611236314121913e-07) units
Optimised parameters =  [0.00910667 0.00274381] 

Covariance matrix = 
 [[ 4.09127504e-15 -2.16084880e-14]
 [-2.16084880e-14  1.47460779e-13]]
chi^2_min = 146972.39828050282
reduced chi^2 = 5249.014224303673
P(chi^2_min, DoF) = 0.0
best fit slope = 0.009106671691422001 units?
best fit intercept = 0.0027438139714859016 units?
[6.39630756e-08 3.84006222e-07]
optimised parameter[0] = (0.009106671691422001 +/- 6.396307557402418e-08) units
optimised parameter[1] = (0.00274381397148590

In [5]:
#9cm
x_values = 0.001*np.array([  463.825,   847.749,  1231.119,  1615.683,  2000.031,  2383.436,
        2768.019,  3135.276,  3327.168,  3710.969,  3902.553,  4287.46 ,
        4670.911,  5055.251,  5438.321,  5822.666,  6206.755,  6590.955,
        6974.853,  7358.207,  7726.11 ,  7918.594,  8110.22 ,  8301.918,
        8493.913,  8685.949,  9069.827,  9454.224,  9838.171, 10221.724])
y_values = 0.001*np.array([  7.499,  11.265,  15.028,  18.804,  22.583,  26.345,  30.099,
        33.867,  35.741,  39.497,  41.368,  45.118,  48.845,  52.554,
        56.253,  59.962,  63.674,  67.377,  71.065,  74.752,  78.442,
        80.278,  82.12 ,  83.958,  85.786,  87.615,  91.281,  94.946,
        98.614, 102.277])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  542.736,   927.893,  1311.376,  1694.694,  2078.313,  2462.682,
        2830.874,  3021.917,  3214.342,  3598.694,  3789.466,  4174.07 ,
        4557.617,  4941.787,  5325.283,  5709.068,  6093.812,  6477.477,
        6845.078,  7037.063,  7245.194,  7613.264,  7805.873,  8189.136,
        8381.082,  8764.968,  9149.401,  9533.113,  9917.43 , 10300.802])
y_values = 0.001*np.array([  7.353,  11.134,  14.898,  18.677,  22.451,  26.207,  29.963,
        31.844,  33.725,  37.464,  39.335,  43.085,  46.841,  50.597,
        54.352,  58.098,  61.848,  65.6  ,  69.344,  71.213,  73.086,
        76.818,  78.678,  82.411,  84.274,  88.005,  91.726,  95.452,
        99.165, 102.88 ])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  510.177,   894.524,  1278.288,  1661.668,  2046.546,  2430.514,
        2798.264,  2990.093,  3182.699,  3373.879,  3566.227,  3949.541,
        4333.646,  4717.824,  5102.313,  5485.515,  5869.964,  6253.618,
        6636.806,  7020.598,  7388.558,  7772.825,  7965.227,  8156.512,
        8540.157,  8924.757,  9309.287,  9693.058, 10076.268, 10460.827])
y_values = 0.001*np.array([  7.474,  11.254,  15.03 ,  18.801,  22.568,  26.335,  30.073,
        31.941,  33.808,  35.674,  37.542,  41.273,  44.993,  48.701,
        52.392,  56.097,  59.791,  63.477,  67.154,  70.834,  74.528,
        78.192,  80.027,  81.871,  85.57 ,  89.261,  92.952,  96.637,
       100.312, 103.984])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.00971677817019404, 0.0097958875927179, 0.009688803619641608])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.00971678 0.00325998] 

Covariance matrix = 
 [[ 4.00552089e-15 -2.21120586e-14]
 [-2.21120586e-14  1.55400638e-13]]
chi^2_min = 701627.7209125618
reduced chi^2 = 25058.13288973435
P(chi^2_min, DoF) = 0.0
best fit slope = 0.00971677817019404 units?
best fit intercept = 0.0032599774384069967 units?
[6.32891846e-08 3.94208877e-07]
optimised parameter[0] = (0.00971677817019404 +/- 6.328918458721108e-08) units
optimised parameter[1] = (0.0032599774384069967 +/- 3.942088766570776e-07) units
Optimised parameters =  [0.00979589 0.00215195] 

Covariance matrix = 
 [[ 4.11398027e-15 -2.24259246e-14]
 [-2.24259246e-14  1.55580419e-13]]
chi^2_min = 195382.7932628946
reduced chi^2 = 6977.956902246236
P(chi^2_min, DoF) = 0.0
best fit slope = 0.0097958875927179 units?
best fit intercept = 0.0021519457162060694 units?
[6.41403170e-08 3.94436838e-07]
optimised parameter[0] = (0.0097958875927179 +/- 6.414031703771098e-08) units
optimised parameter[1] = (0.0021519457162060694 +

In [9]:
#10cm
x_values = 0.001*np.array([  524.863,   909.19 ,  1293.335,  1676.878,  2061.192,  2445.106,
        2828.923,  3212.127,  3596.927,  3980.489,  4349.046,  4541.051,
        4733.114,  5117.232,  5500.971,  5883.9  ,  6268.595,  6652.095,
        7035.821,  7420.236,  7804.275,  8188.214,  8571.572,  8939.922,
        9131.6  ,  9323.253,  9515.883,  9707.43 , 10091.155, 10475.288])
y_values = 0.001*np.array([  8.093,  12.114,  16.125,  20.141,  24.165,  28.177,  32.176,
        36.187,  40.195,  44.198,  48.201,  50.203,  52.203,  56.206,
        60.208,  64.214,  68.199,  72.182,  76.169,  80.144,  84.098,
        88.058,  92.021,  95.99 ,  97.966,  99.948, 101.932, 103.912,
       107.871, 111.83 ])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  510.626,   894.754,  1278.32 ,  1662.097,  2046.389,  2430.204,
        2813.667,  3197.367,  3580.871,  3964.979,  4349.247,  4717.487,
        4908.89 ,  5101.612,  5485.287,  5869.18 ,  6252.674,  6636.983,
        7019.972,  7404.808,  7788.203,  8171.82 ,  8555.737,  8940.334,
        9308.23 ,  9500.476,  9691.316,  9883.8  , 10075.899, 10268.039])
y_values = 0.001*np.array([  7.789,  11.81 ,  15.826,  19.835,  23.84 ,  27.837,  31.831,
        35.826,  39.808,  43.785,  47.769,  51.762,  53.747,  55.733,
        59.708,  63.691,  67.663,  71.639,  75.607,  79.575,  83.536,
        87.498,  91.455,  95.409,  99.358, 101.337, 103.315, 105.291,
       107.26 , 109.234])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  446.094,   830.124,  1213.984,  1597.945,  1982.223,  2365.662,
        2749.654,  3133.647,  3501.939,  3693.026,  3885.853,  4076.606,
        4460.608,  4845.092,  5229.544,  5613.475,  5997.331,  6381.134,
        6764.698,  7149.138,  7532.907,  7916.305,  8283.805,  8476.376,
        8668.166,  8860.786,  9052.706,  9435.959,  9820.428, 10204.664])
y_values = 0.001*np.array([  7.173,  11.172,  15.159,  19.15 ,  23.128,  27.11 ,  31.089,
        35.069,  39.065,  41.07 ,  43.064,  45.067,  49.061,  53.05 ,
        57.053,  61.031,  65.009,  68.963,  72.918,  76.876,  80.824,
        84.772,  88.728,  90.708,  92.69 ,  94.669,  96.652, 100.617,
       104.558, 108.488])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.010430598281766113, 0.01039412740862152, 0.010390776549142175])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.0104306  0.00271204] 

Covariance matrix = 
 [[ 3.72540649e-15 -2.13316383e-14]
 [-2.13316383e-14  1.55478072e-13]]
chi^2_min = 197987.8969843885
reduced chi^2 = 7070.996320871018
P(chi^2_min, DoF) = 0.0
best fit slope = 0.010430598281766113 units?
best fit intercept = 0.0027120377899066857 units?
[6.10361080e-08 3.94307078e-07]
optimised parameter[0] = (0.010430598281766113 +/- 6.103610804403055e-08) units
optimised parameter[1] = (0.0027120377899066857 +/- 3.9430707821534773e-07) units
Optimised parameters =  [0.01039413 0.00259232] 

Covariance matrix = 
 [[ 3.68088727e-15 -2.11416994e-14]
 [-2.11416994e-14  1.54763691e-13]]
chi^2_min = 135837.46248064088
reduced chi^2 = 4851.337945737175
P(chi^2_min, DoF) = 0.0
best fit slope = 0.01039412740862152 units?
best fit intercept = 0.00259231715899431 units?
[6.06703163e-08 3.93400166e-07]
optimised parameter[0] = (0.01039412740862152 +/- 6.067031625806114e-08) units
optimised parameter[1] = (0.00259231715899431

In [10]:
#11cm
x_values = 0.001*np.array([ 350.312,  734.223, 1118.044, 1501.682, 1886.257, 2268.977,
       2653.788, 3037.774, 3421.563, 3789.183, 3981.265, 4173.149,
       4365.279, 4556.89 , 4749.127, 5132.951, 5517.252, 5900.744,
       6285.129, 6669.037, 7052.455, 7435.728, 7819.984, 8188.082,
       8379.864, 8572.306, 8764.253, 8955.664, 9147.32 , 9340.381])
y_values = 0.001*np.array([  6.069,  10.322,  14.57 ,  18.806,  23.015,  27.203,  31.392,
        35.598,  39.805,  44.011,  46.114,  48.226,  50.327,  52.417,
        54.506,  58.707,  62.896,  67.088,  71.271,  75.445,  79.622,
        83.796,  87.964,  92.123,  94.201,  96.283,  98.362, 100.438,
       102.518, 104.595])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  429.651,   813.66 ,  1198.172,  1582.201,  1966.119,  2349.566,
        2733.42 ,  3100.758,  3293.406,  3677.249,  3869.803,  4253.825,
        4637.581,  5020.632,  5405.101,  5789.309,  6173.054,  6557.159,
        6940.834,  7323.706,  7692.254,  7884.749,  8076.759,  8268.463,
        8460.471,  8843.833,  9227.8  ,  9611.561,  9994.998, 10379.09 ])
y_values = 0.001*np.array([ 11.51 ,  15.742,  19.951,  24.184,  28.413,  32.657,  36.89 ,
        41.108,  43.221,  47.431,  49.531,  53.735,  57.94 ,  62.142,
        66.344,  70.536,  74.713,  78.895,  83.081,  87.263,  91.465,
        93.559,  95.654,  97.747,  99.836, 104.025, 108.21 , 112.392,
       116.573, 120.749])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 542.598,  926.209, 1310.077, 1693.529, 2077.769, 2446.275,
       2637.119, 2829.102, 3021.471, 3213.681, 3405.983, 3790.011,
       4173.149, 4557.97 , 4941.141, 5324.395, 5708.915, 6092.741,
       6477.184, 6861.21 , 7228.531, 7420.69 , 7613.035, 7804.525,
       7997.001, 8187.972, 8572.125, 8955.437, 9339.374, 9723.452])
y_values = 0.001*np.array([  8.543,  12.787,  17.043,  21.308,  25.56 ,  29.818,  31.949,
        34.076,  36.193,  38.314,  40.431,  44.668,  48.877,  53.09 ,
        57.286,  61.477,  65.674,  69.86 ,  74.065,  78.268,  82.461,
        84.557,  86.659,  88.758,  90.854,  92.951,  97.142, 101.326,
       105.513, 109.699])
y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.010956414783499778, 0.010981599882402184, 0.011010974133173965])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.01095641 0.00237477] 

Covariance matrix = 
 [[ 4.49016338e-15 -2.33112314e-14]
 [-2.33112314e-14  1.54356438e-13]]
chi^2_min = 185222.2732988234
reduced chi^2 = 6615.081189243692
P(chi^2_min, DoF) = 0.0
best fit slope = 0.010956414783499778 units?
best fit intercept = 0.002374768206374623 units?
[6.70086814e-08 3.92882219e-07]
optimised parameter[0] = (0.010956414783499778 +/- 6.700868135622391e-08) units
optimised parameter[1] = (0.002374768206374623 +/- 3.928822191849802e-07) units
Optimised parameters =  [0.0109816  0.00691454] 

Covariance matrix = 
 [[ 3.88599902e-15 -2.14449093e-14]
 [-2.14449093e-14  1.51677197e-13]]
chi^2_min = 236095.09914626347
reduced chi^2 = 8431.967826652266
P(chi^2_min, DoF) = 0.0
best fit slope = 0.010981599882402184 units?
best fit intercept = 0.006914540362990472 units?
[6.23377816e-08 3.89457568e-07]
optimised parameter[0] = (0.010981599882402184 +/- 6.23377816294573e-08) units
optimised parameter[1] = (0.006914540362990472

In [12]:
#12cm
x_values = 0.001*np.array([ 367.045,  751.443, 1119.149, 1311.268, 1502.677, 1695.193,
       1886.478, 2078.918, 2462.561, 2846.941, 3230.842, 3614.679,
       3998.716, 4381.792, 4765.983, 5149.249, 5533.578, 5901.876,
       6094.315, 6285.881, 6478.293, 6669.693, 6862.143, 7245.76 ,
       7629.942, 8013.475, 8397.041, 8780.35 , 9164.922, 9547.995])
y_values = 0.001*np.array([  6.469,  10.957,  15.408,  17.634,  19.848,  22.06 ,  24.267,
        26.478,  30.879,  35.278,  39.675,  44.063,  48.457,  52.856,
        57.225,  61.612,  65.999,  70.389,  72.581,  74.779,  76.981,
        79.173,  81.363,  85.73 ,  90.125,  94.51 ,  98.903, 103.27 ,
       107.649, 112.022])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 543.147,  926.281, 1311.311, 1694.598, 2079.084, 2447.03 ,
       2638.692, 2829.664, 3021.831, 3214.25 , 3405.715, 3790.216,
       4173.442, 4558.534, 4942.421, 5325.643, 5710.201, 6092.764,
       6478.01 , 6861.24 , 7229.317, 7421.559, 7613.66 , 7805.279,
       7997.076, 8189.01 , 8573.434, 8957.33 , 9340.729, 9725.109])
y_values = 0.001*np.array([  8.977,  13.453,  17.922,  22.375,  26.831,  31.295,  33.513,
        35.744,  37.973,  40.203,  42.435,  46.885,  51.325,  55.77 ,
        60.205,  64.631,  69.067,  73.489,  77.901,  82.307,  86.72 ,
        88.925,  91.126,  93.322,  95.526,  97.728, 102.118, 106.513,
       110.908, 115.302])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 461.389,  845.336, 1229.655, 1613.364, 1981.483, 2173.41 ,
       2365.409, 2557.582, 2749.093, 2940.819, 3325.145, 3709.211,
       4092.571, 4476.344, 4860.305, 5244.824, 5628.595, 6011.414,
       6396.54 , 6763.267, 6955.866, 7147.339, 7339.751, 7531.648,
       7723.941, 8107.911, 8491.269, 8875.921, 9259.91 , 9643.71 ])
y_values = 0.001*np.array([  7.723,  12.19 ,  16.632,  21.086,  25.544,  27.77 ,  29.997,
        32.215,  34.437,  36.654,  41.096,  45.525,  49.964,  54.391,
        58.796,  63.197,  67.599,  71.991,  76.384,  80.783,  82.981,
        85.179,  87.379,  89.583,  91.78 ,  96.168, 100.56 , 104.952,
       109.343, 113.724])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.011479034727932843, 0.011581934816945975, 0.01154040090826431])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.01147903 0.002544  ] 

Covariance matrix = 
 [[ 4.48138439e-15 -2.14760199e-14]
 [-2.14760199e-14  1.36252300e-13]]
chi^2_min = 227998.58640168037
reduced chi^2 = 8142.80665720287
P(chi^2_min, DoF) = 0.0
best fit slope = 0.011479034727932843 units?
best fit intercept = 0.0025439954118175153 units?
[6.69431429e-08 3.69123692e-07]
optimised parameter[0] = (0.011479034727932843 +/- 6.694314294700163e-08) units
optimised parameter[1] = (0.0025439954118175153 +/- 3.6912369221109735e-07) units
Optimised parameters =  [0.01158193 0.0028829 ] 

Covariance matrix = 
 [[ 4.56090992e-15 -2.35489777e-14]
 [-2.35489777e-14  1.54921864e-13]]
chi^2_min = 327431.84686352196
reduced chi^2 = 11693.99453084007
P(chi^2_min, DoF) = 0.0
best fit slope = 0.011581934816945975 units?
best fit intercept = 0.002882898056813482 units?
[6.75345091e-08 3.93601148e-07]
optimised parameter[0] = (0.011581934816945975 +/- 6.753450908895362e-08) units
optimised parameter[1] = (0.00288289805681

In [14]:
#13cm
x_values = 0.001*np.array([ 430.289,  814.401, 1198.134, 1581.533, 1965.775, 2349.021,
       2717.552, 2909.47 , 3101.713, 3293.521, 3485.343, 3677.917,
       3869.768, 4253.465, 4637.383, 5021.367, 5405.066, 5789.142,
       6173.063, 6556.471, 6939.926, 7308.535, 7500.67 , 7692.62 ,
       7884.423, 8075.938, 8268.249, 8652.42 , 9036.086, 9419.698])
y_values = 0.001*np.array([  6.796,  11.46 ,  16.116,  20.775,  25.423,  30.061,  34.69 ,
        37.01 ,  39.326,  41.638,  43.952,  46.266,  48.582,  53.215,
        57.844,  62.463,  67.084,  71.69 ,  76.314,  80.935,  85.552,
        90.169,  92.477,  94.784,  97.092,  99.398, 101.705, 106.322,
       110.916, 115.504])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 446.248,  829.199, 1213.844, 1598.121, 1965.866, 2173.934,
       2541.137, 2733.795, 2925.624, 3117.576, 3308.585, 3501.091,
       3885.441, 4268.68 , 4652.317, 5037.165, 5421.317, 5804.997,
       6188.627, 6557.001, 6764.82 , 7131.895, 7324.318, 7516.208,
       7708.647, 7899.933, 8092.559, 8476.537, 8859.482, 9244.041])
y_values = 0.001*np.array([  7.742,  12.383,  17.005,  21.618,  26.233,  28.531,  33.126,
        35.418,  37.708,  40.001,  42.302,  44.596,  49.186,  53.797,
        58.397,  62.986,  67.568,  72.15 ,  76.738,  81.318,  83.611,
        88.185,  90.477,  92.765,  95.052,  97.344,  99.632, 104.201,
       108.772, 113.341])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 477.948,  861.525, 1245.895, 1628.81 , 2013.313, 2398.135,
       2781.841, 3165.504, 3548.988, 3933.799, 4301.561, 4493.65 ,
       4685.525, 4876.943, 5068.938, 5261.378, 5645.11 , 6029.103,
       6412.396, 6796.591, 7181.085, 7564.471, 7948.846, 8332.78 ,
       8716.217, 9083.549, 9275.623, 9467.521, 9659.896, 9851.38 ])
y_values = 0.001*np.array([ 10.209,  14.851,  19.489,  24.131,  28.755,  33.369,  37.998,
        42.631,  47.254,  51.875,  56.493,  58.799,  61.102,  63.404,
        65.707,  68.009,  72.613,  77.219,  81.815,  86.427,  91.025,
        95.629, 100.243, 104.839, 109.431, 114.02 , 116.32 , 118.611,
       120.9  , 123.187])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.012092881135651554, 0.012000156766687716, 0.01205017772797926])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.01209288 0.00171728] 

Covariance matrix = 
 [[ 4.81490778e-15 -2.40759759e-14]
 [-2.40759759e-14  1.53720393e-13]]
chi^2_min = 163427.34473264025
reduced chi^2 = 5836.690883308581
P(chi^2_min, DoF) = 0.0
best fit slope = 0.012092881135651554 units?
best fit intercept = 0.0017172829802372463 units?
[6.93895365e-08 3.92071923e-07]
optimised parameter[0] = (0.012092881135651554 +/- 6.938953654228396e-08) units
optimised parameter[1] = (0.0017172829802372463 +/- 3.920719228967433e-07) units
Optimised parameters =  [0.01200016 0.00252973] 

Covariance matrix = 
 [[ 4.96611847e-15 -2.43652689e-14]
 [-2.43652689e-14  1.52876667e-13]]
chi^2_min = 161095.55540224194
reduced chi^2 = 5753.412692937212
P(chi^2_min, DoF) = 0.0
best fit slope = 0.012000156766687716 units?
best fit intercept = 0.0025297288563042165 units?
[7.04706923e-08 3.90994459e-07]
optimised parameter[0] = (0.012000156766687716 +/- 7.047069228607096e-08) units
optimised parameter[1] = (0.0025297288563

In [16]:
#14cm
x_values = 0.001*np.array([ 477.782,  669.647, 1053.771, 1437.155, 1820.661, 2204.784,
       2589.505, 2973.16 , 3357.208, 3741.073, 4124.866, 4491.854,
       4684.12 , 4875.559, 5068.552, 5260.139, 5452.266, 5644.121,
       6027.341, 6220.012, 6604.454, 6988.268, 7371.802, 7756.239,
       8139.884, 8523.001, 8907.464, 9275.294, 9467.221, 9659.73 ])
y_values = 0.001*np.array([  8.974,  11.379,  16.185,  20.983,  25.785,  30.601,  35.413,
        40.232,  45.053,  49.853,  54.658,  59.448,  61.839,  64.229,
        66.628,  69.03 ,  71.42 ,  73.812,  78.601,  80.989,  85.734,
        90.489,  95.257, 100.014, 104.768, 109.522, 114.281, 119.035,
       121.415, 123.802])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 463.159,  847.39 , 1231.324, 1599.224, 1790.998, 1982.638,
       2175.166, 2367.406, 2750.794, 3134.682, 3518.626, 3902.793,
       4286.393, 4669.954, 5054.078, 5437.574, 5821.863, 6189.753,
       6397.662, 6766.087, 6957.228, 7149.261, 7342.22 , 7534.017,
       7917.28 , 8300.566, 8684.67 , 9068.946, 9452.81 , 9837.292])
y_values = 0.001*np.array([  7.998,  12.837,  17.683,  22.515,  24.921,  27.337,  29.76 ,
        32.179,  37.011,  41.836,  46.654,  51.478,  56.297,  61.105,
        65.93 ,  70.746,  75.544,  80.334,  82.738,  87.545,  89.944,
        92.35 ,  94.749,  97.142, 101.938, 106.727, 111.503, 116.283,
       121.064, 125.84 ])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 414.738,  607.05 ,  990.98 , 1374.428, 1758.893, 2142.648,
       2526.175, 2909.97 , 3293.116, 3677.684, 4061.235, 4430.265,
       4622.151, 4813.831, 5005.755, 5198.05 , 5581.334, 5964.753,
       6349.099, 6732.314, 7117.04 , 7500.226, 7884.829, 8269.015,
       8652.239, 9020.902, 9212.444, 9404.419, 9595.771, 9788.728])
y_values = 0.001*np.array([  7.972,  10.385,  15.217,  20.036,  24.856,  29.679,  34.501,
        39.328,  44.138,  48.935,  53.747,  58.563,  60.969,  63.378,
        65.785,  68.189,  73.003,  77.803,  82.601,  87.405,  92.207,
        96.992, 101.779, 106.571, 111.373, 116.16 , 118.551, 120.939,
       123.334, 125.731])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.012503940479402124, 0.012572649059163731, 0.012563290493273687])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.01250394 0.0030994 ] 

Covariance matrix = 
 [[ 4.53692134e-15 -2.34206345e-14]
 [-2.34206345e-14  1.54236043e-13]]
chi^2_min = 356624.8204486736
reduced chi^2 = 12736.600730309772
P(chi^2_min, DoF) = 0.0
best fit slope = 0.012503940479402124 units?
best fit intercept = 0.00309940292030732 units?
[6.73566726e-08 3.92728969e-07]
optimised parameter[0] = (0.012503940479402124 +/- 6.73566725922764e-08) units
optimised parameter[1] = (0.00309940292030732 +/- 3.9272896909137216e-07) units
Optimised parameters =  [0.01257265 0.00236671] 

Covariance matrix = 
 [[ 4.33442581e-15 -2.20523810e-14]
 [-2.20523810e-14  1.45529853e-13]]
chi^2_min = 267701.06966864085
reduced chi^2 = 9560.752488165745
P(chi^2_min, DoF) = 0.0
best fit slope = 0.012572649059163731 units?
best fit intercept = 0.0023667088133299125 units?
[6.58363563e-08 3.81483752e-07]
optimised parameter[0] = (0.012572649059163731 +/- 6.583635627611102e-08) units
optimised parameter[1] = (0.00236670881332991

In [18]:
#15cm
x_values = 0.001*np.array([  397.654,   782.505,  1150.582,  1358.613,  1726.143,  1917.729,
        2109.242,  2493.37 ,  2877.051,  3261.523,  3645.418,  4029.147,
        4412.893,  4797.698,  5180.881,  5564.814,  5948.722,  6316.707,
        6508.464,  6701.201,  7084.646,  7276.504,  7661.104,  8044.963,
        8428.882,  8812.328,  9196.428,  9580.309,  9964.397, 10348.15 ])
y_values = 0.001*np.array([  8.587,  13.627,  18.654,  21.167,  26.164,  28.661,  31.155,
        36.15 ,  41.138,  46.129,  51.119,  56.111,  61.101,  66.088,
        71.075,  76.062,  81.052,  86.036,  88.525,  91.009,  95.983,
        98.473, 103.446, 108.408, 113.385, 118.357, 123.326, 128.291,
       133.253, 138.225])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  542.097,   925.851,  1309.485,  1693.487,  2078.21 ,  2461.468,
        2828.772,  3021.785,  3213.952,  3405.487,  3789.35 ,  4173.121,
        4556.335,  4940.206,  5324.39 ,  5708.775,  6092.168,  6476.618,
        6861.09 ,  7228.112,  7420.206,  7611.307,  7996.676,  8187.522,
        8380.741,  8763.661,  8955.104,  9339.577,  9724.279, 10107.579])
y_values = 0.001*np.array([ 10.477,  15.498,  20.519,  25.528,  30.54 ,  35.548,  40.563,
        43.069,  45.58 ,  48.085,  53.089,  58.093,  63.097,  68.081,
        73.066,  78.045,  83.021,  87.993,  92.964,  97.937, 100.43 ,
       102.913, 107.874, 110.355, 112.842, 117.808, 120.286, 125.248,
       130.206, 135.157])



y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([ 382.064,  765.405, 1149.696, 1532.7  , 1901.709, 2093.233,
       2285.085, 2477.781, 2669.   , 3052.575, 3436.678, 3820.054,
       4205.16 , 4589.033, 4971.888, 5355.517, 5740.348, 6123.968,
       6492.951, 6684.189, 6876.71 , 7067.828, 7260.495, 7643.669,
       8027.882, 8411.875, 8795.523, 9179.205, 9563.747, 9947.354])
y_values = 0.001*np.array([  8.662,  13.687,  18.707,  23.73 ,  28.746,  31.257,  33.758,
        36.26 ,  38.762,  43.764,  48.76 ,  53.764,  58.752,  63.736,
        68.72 ,  73.697,  78.677,  83.662,  88.639,  91.127,  93.613,
        96.107,  98.6  , 103.569, 108.539, 113.503, 118.46 , 123.415,
       128.378, 133.341])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.013022971414281295, 0.013039525781486054, 0.01303288794292374])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [0.01302297 0.00362074] 

Covariance matrix = 
 [[ 3.80448514e-15 -1.99834476e-14]
 [-1.99834476e-14  1.38298439e-13]]
chi^2_min = 262758.55415885034
reduced chi^2 = 9384.234077101797
P(chi^2_min, DoF) = 0.0
best fit slope = 0.013022971414281295 units?
best fit intercept = 0.0036207441620990364 units?
[6.16805086e-08 3.71884981e-07]
optimised parameter[0] = (0.013022971414281295 +/- 6.168050860183804e-08) units
optimised parameter[1] = (0.0036207441620990364 +/- 3.7188498082708525e-07) units
Optimised parameters =  [0.01303953 0.00356461] 

Covariance matrix = 
 [[ 4.17221322e-15 -2.26853542e-14]
 [-2.26853542e-14  1.56679210e-13]]
chi^2_min = 329816.75461325
reduced chi^2 = 11779.169807616072
P(chi^2_min, DoF) = 0.0
best fit slope = 0.013039525781486054 units?
best fit intercept = 0.003564610458622395 units?
[6.45926716e-08 3.95827248e-07]
optimised parameter[0] = (0.013039525781486054 +/- 6.459267158114867e-08) units
optimised parameter[1] = (0.003564610458622

In [20]:
#16cm
x_values = 0.001*np.array([ 399.861,  590.911,  783.115,  975.693, 1166.862, 1550.441,
       1934.328, 2318.871, 2702.935, 3087.148, 3471.219, 3855.013,
       4238.842, 4622.814, 4990.817, 5182.175, 5374.589, 5566.197,
       5758.369, 5949.51 , 6142.007, 6526.285, 6909.86 , 7294.318,
       7677.311, 8061.609, 8444.664, 8828.233, 9212.297, 9581.59 ])
y_values = 0.001*np.array([  4.599,   7.337,   9.968,  12.571,  15.172,  20.364,  25.57 ,
        30.756,  35.943,  41.133,  46.313,  51.486,  56.666,  61.838,
        67.007,  69.599,  72.189,  74.775,  77.363,  79.944,  82.527,
        87.699,  92.865,  98.018, 103.169, 108.321, 113.48 , 118.636,
       123.791, 128.928])

y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  382.511,   765.478,  1149.844,  1533.628,  1917.778,  2302.423,
        2685.583,  3069.057,  3452.97 ,  3836.754,  4205.435,  4397.626,
        4589.645,  4781.171,  4972.539,  5165.152,  5548.945,  5932.935,
        6316.997,  6700.165,  7084.243,  7467.714,  7852.282,  8236.762,
        8620.14 ,  8988.588,  9196.538,  9563.884,  9755.824, 10139.698])
y_values = 0.001*np.array([  9.075,  14.283,  19.492,  24.707,  29.909,  35.114,  40.323,
        45.525,  50.722,  55.914,  61.111,  63.711,  66.311,  68.903,
        71.494,  74.079,  79.255,  84.438,  89.618,  94.783,  99.946,
       105.113, 110.273, 115.437, 120.611, 125.766, 128.342, 133.507,
       136.09 , 141.252])



y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))

x_values = 0.001*np.array([  509.292,   894.052,  1278.449,  1661.141,  2030.152,  2221.655,
        2412.62 ,  2798.035,  3181.388,  3564.677,  3949.47 ,  4333.048,
        4716.948,  5100.621,  5485.344,  5868.409,  6252.969,  6619.927,
        6812.922,  7004.339,  7388.03 ,  7580.48 ,  7964.356,  8347.135,
        8732.138,  9115.791,  9500.206,  9883.875, 10267.377, 10650.722])
y_values = 0.001*np.array([  9.946,  15.153,  20.376,  25.575,  30.748,  33.339,  35.923,
        41.104,  46.297,  51.486,  56.667,  61.852,  67.023,  72.184,
        77.346,  82.512,  87.685,  92.855,  95.439,  98.02 , 103.173,
       105.75 , 110.904, 116.063, 121.22 , 126.374, 131.524, 136.669,
       141.821, 146.975])


y_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                           0.001,0.001])

x_errors = 0.001*np.array([0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,
                             0.001,0.001])

def model_function(x, *params):
    return params[0]*x + params[1]


initial_values = numpy.array([0.005, 0.005]) # Initial guess for fit parameters

def chi_squared(model_params, model, x_data, y_data, y_err):
    return numpy.sum(((y_data - model(x_data, *model_params))/y_err)**2) # Note the `*model_params' here!

degrees_of_freedom = x_values.size - initial_values.size

popt, cov = scipy.optimize.curve_fit(model_function, # function to fit
                                     x_values, # x data
                                     y_values, # y data
                                     sigma=y_errors, # array of error bars for the fit
                                     absolute_sigma=True, # errors bars DO represent 1 std error
                                     p0=initial_values, # starting point for fit
                                     check_finite=True) # raise ValueError if NaN encountered (don't allow errors to pass)

print('Optimised parameters = ', popt, '\n')
print('Covariance matrix = \n', cov)

chi_squared_min = chi_squared(popt, model_function, x_values, y_values, y_errors)
print('chi^2_min = {}'.format(chi_squared_min))
print('reduced chi^2 = {}'.format(chi_squared_min/degrees_of_freedom))
print('P(chi^2_min, DoF) = {}'.format(scipy.stats.chi2.sf(chi_squared_min, degrees_of_freedom)))

print('best fit slope = {} units?'.format(popt[0]))
print('best fit intercept = {} units?'.format(popt[1]))

popt_errs = numpy.sqrt(numpy.diag(cov))
print(popt_errs)

for i, (val, err) in enumerate(zip(popt, popt_errs)):
    print('optimised parameter[{}] = ({} +/- {}) units'.format(i, val, err))
    
gradients = np.array([0.013520893794201577, 0.013541626051037743, 0.013510661518075496])

print(np.mean(gradients))
print(np.std(gradients)/np.sqrt(len(gradients)))

Optimised parameters =  [ 0.01352089 -0.00060455] 

Covariance matrix = 
 [[ 4.42803588e-15 -2.11361793e-14]
 [-2.11361793e-14  1.34221877e-13]]
chi^2_min = 211254.60496035588
reduced chi^2 = 7544.80732001271
P(chi^2_min, DoF) = 0.0
best fit slope = 0.013520893794201577 units?
best fit intercept = -0.0006045460390845522 units?
[6.65434887e-08 3.66363040e-07]
optimised parameter[0] = (0.013520893794201577 +/- 6.654348866445462e-08) units
optimised parameter[1] = (-0.0006045460390845522 +/- 3.6636303965900637e-07) units
Optimised parameters =  [0.01354163 0.00400507] 

Covariance matrix = 
 [[ 4.08971282e-15 -2.18952749e-14]
 [-2.18952749e-14  1.50555030e-13]]
chi^2_min = 289149.5054813785
reduced chi^2 = 10326.768052906376
P(chi^2_min, DoF) = 0.0
best fit slope = 0.013541626051037743 units?
best fit intercept = 0.004005072407835699 units?
[6.39508625e-08 3.88014213e-07]
optimised parameter[0] = (0.013541626051037743 +/- 6.395086251361407e-08) units
optimised parameter[1] = (0.0040050724